{{- range $stsname, $sts := .Values.statefulset }}
{{- range $kcntnr, $cntnr := $sts.containers }}
{{- range $kprt, $prt := $cntnr.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $stsname }}-{{ $prt.name }}
  labels:
    {{- include "blockchain-node.labels" $ | nindent 4 }}
spec:
  selector:
    statefulsetname: {{ $stsname }}
  type: {{ $prt.type }}
  ports:
    - port: {{ $prt.port }}
      targetPort: {{ $prt.port }}
      protocol: {{ $prt.protocol }}
      name: {{ $prt.name }}
{{- end -}}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $stsname }}
  labels:
    {{- include "blockchain-node.labels" $ | nindent 4 }}
spec:
  selector:
    statefulsetname: {{ $stsname }}
  clusterIP: None
  ports:
    - port: 12345
{{- end -}}
